widgetify-app/widgetify-extension

src/layouts/arzLive/arzLive.layout.tsx
مربوط به https://github.com/widgetify-app/widgetify-extension/issues/21
=> fix(currency-list): rotate expand button icon if currency list expanded

src/layouts/wigiArz/wigi_arz.layout.tsx
مربوط به 
https://github.com/widgetify-app/widgetify-extension/issues/36
=> fix(comboWidget): correct arz list overflow height in combo widget

src/common/constant/store.key.ts, src/context/todo.context.tsx, src/layouts/widgetify-card/overviewCards/google.overviewCard.tsx, src/layouts/widgetify-card/overviewCards/todo-overviewCard.tsx, src/layouts/widgetify-card/widgetify.layout.tsx, src/layouts/widgets/calendar/utils.ts, src/layouts/widgets/todos/expandable-todo-input.tsx, src/layouts/widgets/todos/todo.item.tsx, src/layouts/widgets/todos/todos.tsx
=> feat(todos): add view mode (day/monthly)

src/layouts/widgets/wigiPad/clock-display/clock-display.tsx, src/layouts/widgets/wigiPad/clock-display/clocks/analog.clock.tsx, src/layouts/widgets/wigiPad/clock-display/clocks/digital.clock.tsx
- Remove dependency on getCurrentDate and WidgetifyDate
- Use standard JavaScript Date methods (getHours, getMinutes, getSeconds)
- Implement proper timezone handling with Intl.DateTimeFormat API
- Move timezone label formatting to DigitalClock component
- Fix analog clock display orientation
=> refactor: replace custom date utilities with native Date objects #102

src/layouts/widgets/notes/components/note-navigation.tsx, src/layouts/widgets/todos/todo.item.tsx
- Replace text-base-content with text-base in note navigation icons
- Update disabled state styling from opacity-30 to text-muted for delete button
- Replace btn-primary disabled styling with explicit text-white class
- Change priority badge backgrounds from solid to semi-transparent (bg-{color}/10)
- Update priority text colors from {color}-content to {color} for better contrast
=> refactor: update color classes for better visual consistency

src/layouts/navbar/navbar.layout.tsx
=> Adding marginTop to navBar (for md: and lg:)

src/layouts/widgets/wigiArz/components/currency-box.tsx, src/layouts/widgets/wigiArz/wigi_arz.layout.tsx
In this commit:
- Align the combo components' style with the new design
=> Refactor Combo Widget 

src/layouts/widgets/calendar/calendar.tsx, src/layouts/widgets/calendar/components/calendar-grid.tsx, src/layouts/widgets/calendar/components/calendar-header.tsx, src/layouts/widgets/calendar/components/day-summary.tsx, src/layouts/widgets/calendar/components/day/day.tsx
In this commit:
improve calendar UI with the new redesign, and fix the overflowing section
- Fixed the overflowing summary day section 
- Make the components fit the new design
=> Refactor Calendar Widget UI

src/layouts/widgets/wigiPad/date-display/date.display.tsx, src/layouts/widgets/wigiPad/wigiPad.layout.tsx
=> feat(DateDisplay): enhance date display with holiday visual indicators

src/layouts/widgets/todos/todos.tsx
Fix todos button styling in edge
=> Fix todos button styling in edge

package-lock.json, src/components/auth/require-auth.tsx, src/pages/home.tsx
Synced the Auth Required wrapper syncde with new design
=> Synced the Auth Required Component UI

package-lock.json, src/layouts/bookmark/bookmarks.tsx, src/layouts/bookmark/components/bookmark-item.tsx
Fixes #110
This PR fixes the issue where middle-click on bookmarks wouldn't work while scrolling when widgets overflow.
Related to issue #110.
=> Fix middle-click not working when widget is scrollable

src/layouts/widgets/todos/todo.item.tsx
=> feat: add undo functionality for todo deletion with 5-second countdown

src/layouts/widgets/wigiPad/info-panel/components/email-message-item.tsx, src/layouts/widgets/wigiPad/info-panel/hooks/useInfoPanelData.ts, src/layouts/widgets/wigiPad/info-panel/info-panel.tsx, src/layouts/widgets/wigiPad/info-panel/tabs/email/email-tab.tsx, src/services/hooks/extension/getWigiPadData.hook.ts
- Add EmailMessageItem component for displaying email messages
- Create EmailTab for email section in info panel
- Update useInfoPanelData hook to handle email messages
- Integrate email tab into main InfoPanel component
- Add email message interfaces and data structures
=> feat: add email messages support to wigiPad info panel

src/layouts/bookmark/components/bookmark-suggestions.tsx, src/layouts/bookmark/components/modal/add-bookmark.modal.tsx, src/layouts/bookmark/components/shared.tsx
=> feat: add bookmark suggestions to add bookmark modal

src/layouts/setting/tabs/account/activity-input.tsx, src/layouts/setting/tabs/account/connections.tsx, src/layouts/setting/tabs/account/user-profile.tsx, src/services/hooks/user/userService.hook.ts
- Redesign profile card with modern gradient background and better layout
- Add birthday field display to user profile
- Apply consistent rounded-2xl styling across all buttons
- Improve responsive design with flexible layout
- Add size props to section panels for better spacing
=> refactor: improve user profile UI design and styling

bun.lock, package.json, src/layouts/navbar/navbar.layout.tsx, src/layouts/widgets/wigiPad/info-panel/components/ann-item.tsx, src/layouts/widgets/wigiPad/info-panel/info-panel.tsx
- Add DOMPurify package for secure HTML content sanitization
- Sanitize logo content in navbar with allowed tags and attributes
- Implement secure HTML rendering for notification items
- Define strict allowlist for HTML tags (div, b, i, em, strong, a, p, br, span, ul, li, img)
- Define safe attribute allowlist (href, target, rel, class, src, alt)
- Simplify notification item component structure
- Remove unsafe dangerouslySetInnerHTML usage without sanitization
This prevents XSS attacks while maintaining rich content functionality for logos and notifications from the server.
=> feat(security): implement HTML sanitization to prevent XSS attacks

src/common/constant/store.key.ts, src/layouts/widgets/wigiPad/clock-display/components/clock-settings-modal.tsx, src/layouts/widgets/wigiPad/date-display/components/date-settings-modal.tsx, src/layouts/widgets/wigiPad/date-display/components/holiday.badge.tsx, src/layouts/widgets/wigiPad/date-display/date.display.tsx, src/layouts/widgets/wigiPad/date-display/dates/gregorian.date.tsx, src/layouts/widgets/wigiPad/date-display/dates/jalali.date.tsx, src/layouts/widgets/wigiPad/date-display/types.ts
=> feat: add date format selection (Jalali/Gregorian) to WigiPad

src/layouts/widgets/wigiArz/components/currency-box.tsx, src/layouts/widgets/wigiArz/components/currency-modal.tsx, src/layouts/widgets/wigiArz/utils/getPrice.tsx
- Add GetPrice utility for formatted price rendering
- Remove displayPrice state and use GetPrice in CurrencyBox
- Update CurrencyModal to use GetPrice, adjust layout and remove chart section
- Fix price change calculation to use rialPrice
=> refactor: update currency display logic and modal components

src/layouts/widgets/wigiPad/clock-display/clock-display.tsx, src/layouts/widgets/wigiPad/clock-display/clock-setting.interface.ts, src/layouts/widgets/wigiPad/clock-display/clock-setting.tsx, src/layouts/widgets/wigiPad/clock-display/clocks/analog.clock.tsx, src/layouts/widgets/wigiPad/clock-display/clocks/digital.clock.tsx
- Add useSelectedFont setting to allow custom font selection in clock display
- Optimize digital clock rendering with useMemo for style calculations
- Refactor seconds animation SVG logic for better readability
- Improve conditional styling performance with memoized values
- Add toggle option for selected font usage in clock settings
=> feat: add font customization and improve digital clock performance

src/components/toolTip.tsx, src/context/notes.context.tsx, src/layouts/widgets/notes/components/note-navigation.tsx, src/layouts/widgets/notes/notes.layout.tsx, src/pages/home.tsx, src/pages/home/content-section.tsx, src/services/note/note-api.ts
- Add note list view when no active note is selected
- Implement create/delete note confirmation with tooltip
- Add loading states for note creation and saving operations
- Improve note navigation with back-to-list functionality
- Update API integration for proper note CRUD operations
- Add Persian date formatting for note timestamps
- Enhance error handling with toast notifications
- Remove keyboard sensor from DnD to prevent space key conflicts
- Add tooltip positioning options (bottom-right, bottom-left, top-right, top-left)
- Add alwaysShow prop to tooltip component for persistent display
=> feat: enhance notepad widget with improved UI and functionality
